# Generated by Django 4.0.3 on 2022-06-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='contact_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='contact_role',
            field=models.CharField(max_length=100, null=True, verbose_name='Contact Role'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='progress',
            field=models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default=('AC', 'Active'), max_length=100, verbose_name='Status'),
        ),
    ]
