# Generated by Django 4.0.3 on 2022-06-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='contact_company',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsmodel', verbose_name='Contact Company'),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='contact_opp',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunitiesmodel', verbose_name='Contact Opportunity'),
        ),
    ]
