# Generated by Django 4.0.3 on 2022-06-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Account Name')),
                ('account_ind', models.CharField(choices=[('AFS', 'Accommodation and Food Service Activities'), ('ASP', 'Administrative and Support Service Activities'), ('AFF', 'Agriculture, Forestry and Fishing'), ('AER', 'Arts, Entertainment and Recreation'), ('CON', 'Construction'), ('EDU', 'Education'), ('EGA', 'Electricity, Gas, Steam and Air Conditioning Supply'), ('FII', 'Financial and Insurance Activities'), ('HSW', 'Human Health and Social Work Activities'), ('ICO', 'Information and Communication'), ('MAN', 'Manufacturing'), ('MIQ', 'Mining and Quarrying'), ('OTH', 'Other Service Activities'), ('PST', 'Professional, Scientific and Technical Activities'), ('RES', 'Real Estate Activities'), ('TRS', 'Transportation and Storage'), ('WWM', 'Water Supply: Sewerage, Waste Management and Remediation Activities'), ('WRT', 'Wholesale and Retail Trade'), ('ADF', 'Advisory & Financial Services'), ('CGS', 'Consumer Goods & Services'), ('ONR', 'Online Retail'), ('EIC', 'Specialist Engineering, Infrastructure & Contractors'), ('TEC', 'Technology')], max_length=3, null=True, verbose_name='Account Industry')),
                ('account_size', models.PositiveIntegerField(null=True, verbose_name='# of Employees')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('progress', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default=('AC', 'Active'), max_length=2, verbose_name='Status')),
                ('slug', models.SlugField(default='', editable=False, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
    ]
