# Generated by Django 4.0.3 on 2022-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='progress',
            field=models.CharField(choices=[('Op', 'Open (New)'), ('Ip', 'In Progress'), ('Cw', 'Closed Won'), ('Cl', 'Closed Lost')], default='Op', max_length=2),
        ),
    ]
