# Generated by Django 4.0.3 on 2022-05-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountsmodel_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='account_ind',
            field=models.CharField(choices=[('AFS', 'Accommodation and Food Service Activities'), ('ASP', 'Administrative and Support Service Activities'), ('AFF', 'Agriculture, Forestry and Fishing'), ('AER', 'Arts, Entertainment and Recreation'), ('CON', 'Construction'), ('EDU', 'Education'), ('EGA', 'Electricity, Gas, Steam and Air Conditioning Supply'), ('FII', 'Financial and Insurance Activities'), ('HSW', 'Human Health and Social Work Activities'), ('ICO', 'Information and Communication'), ('MAN', 'Manufacturing'), ('MIQ', 'Mining and Quarrying'), ('OTH', 'Other Service Activities'), ('PST', 'Professional, Scientific and Technical Activities'), ('RES', 'Real Estate Activities'), ('TRS', 'Transportation and Storage'), ('WWM', 'Water Supply: Sewerage, Waste Management and Remediation Activities'), ('WRT', 'Wholesale and Retail Trade'), ('ADF', 'Advisory & Financial Services'), ('CGS', 'Consumer Goods & Services'), ('ONR', 'Online Retail'), ('EIC', 'Specialist Engineering, Infrastructure & Contractors'), ('TEC', 'Technology')], max_length=3, null=True, verbose_name='Account Industry'),
        ),
        migrations.AlterField(
            model_name='accountsmodel',
            name='progress',
            field=models.CharField(choices=[('Op', 'Open (New)'), ('Ip', 'In Progress'), ('Cw', 'Closed Won'), ('Cl', 'Closed Lost')], default=('Op', 'Open (New)'), max_length=2, verbose_name='Progress'),
        ),
    ]
