# Generated by Django 4.0.3 on 2022-06-02 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=50, null=True, verbose_name='Opportunity Name')),
                ('opportunity_value', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Opportunity Value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('progress', models.CharField(choices=[('Op', 'Open (New)'), ('Ip', 'In Progress'), ('Cw', 'Closed Won'), ('Cl', 'Closed Lost')], default=('Op', 'Open (New)'), max_length=2, verbose_name='Status')),
                ('slug', models.SlugField(default='', editable=False)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsmodel', verbose_name='Opportunity Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Opportunitie',
            },
        ),
    ]
