# Generated by Django 4.0.3 on 2022-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
