# Generated by Django 4.0.3 on 2022-06-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='opportunity_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Opportunity Name'),
        ),
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='progress',
            field=models.CharField(choices=[('Op', 'Open (New)'), ('Ip', 'In Progress'), ('Cw', 'Closed Won'), ('Cl', 'Closed Lost')], default=('Op', 'Open (New)'), max_length=100, verbose_name='Status'),
        ),
    ]
