# Generated by Django 4.0.3 on 2022-05-18 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitiesmodel',
            options={'verbose_name': 'Opportunitie'},
        ),
        migrations.RemoveField(
            model_name='opportunitiesmodel',
            name='opportunity_company',
        ),
        migrations.AddField(
            model_name='opportunitiesmodel',
            name='opportunity_value',
            field=models.PositiveIntegerField(null=True, verbose_name='Opportunity Value'),
        ),
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsmodel', verbose_name='Opportunity Account'),
        ),
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='opportunity_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Opportunity Name'),
        ),
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
