# Generated by Django 4.0.3 on 2022-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunitiesmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='opportunity_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Opportunity Value'),
        ),
    ]
