# Generated by Django 4.0.3 on 2022-06-02 19:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunitiesmodel_opportunity_value_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitiesmodel',
            name='opportunity_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='GBP', max_digits=20, null=True, verbose_name='Opportunity Value'),
        ),
    ]
