# Generated by Django 4.0.3 on 2022-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunitiesmodel_opportunity_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitiesmodel',
            name='progress',
            field=models.CharField(choices=[('Op', 'Open (New)'), ('Ip', 'In Progress'), ('Cw', 'Closed Won'), ('Cl', 'Closed Lost')], default=('Op', 'Open (New)'), max_length=2, verbose_name='Status'),
        ),
    ]
